<?php
/**
 * GetRateLimit200ResponseData
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * OneLogin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0.0-alpha.1
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.0.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * GetRateLimit200ResponseData Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class GetRateLimit200ResponseData implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'getRateLimit_200_response_data';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'x_rate_limit_limit' => 'int',
        'x_rate_limit_remaining' => 'int',
        'x_rate_limit_reset' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'x_rate_limit_limit' => null,
        'x_rate_limit_remaining' => null,
        'x_rate_limit_reset' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'x_rate_limit_limit' => 'X-RateLimit-Limit',
        'x_rate_limit_remaining' => 'X-RateLimit-Remaining',
        'x_rate_limit_reset' => 'X-RateLimit-Reset'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'x_rate_limit_limit' => 'setXRateLimitLimit',
        'x_rate_limit_remaining' => 'setXRateLimitRemaining',
        'x_rate_limit_reset' => 'setXRateLimitReset'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'x_rate_limit_limit' => 'getXRateLimitLimit',
        'x_rate_limit_remaining' => 'getXRateLimitRemaining',
        'x_rate_limit_reset' => 'getXRateLimitReset'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['x_rate_limit_limit'] = $data['x_rate_limit_limit'] ?? null;
        $this->container['x_rate_limit_remaining'] = $data['x_rate_limit_remaining'] ?? null;
        $this->container['x_rate_limit_reset'] = $data['x_rate_limit_reset'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets x_rate_limit_limit
     *
     * @return int|null
     */
    public function getXRateLimitLimit()
    {
        return $this->container['x_rate_limit_limit'];
    }

    /**
     * Sets x_rate_limit_limit
     *
     * @param int|null $x_rate_limit_limit x_rate_limit_limit
     *
     * @return self
     */
    public function setXRateLimitLimit($x_rate_limit_limit)
    {
        $this->container['x_rate_limit_limit'] = $x_rate_limit_limit;

        return $this;
    }

    /**
     * Gets x_rate_limit_remaining
     *
     * @return int|null
     */
    public function getXRateLimitRemaining()
    {
        return $this->container['x_rate_limit_remaining'];
    }

    /**
     * Sets x_rate_limit_remaining
     *
     * @param int|null $x_rate_limit_remaining x_rate_limit_remaining
     *
     * @return self
     */
    public function setXRateLimitRemaining($x_rate_limit_remaining)
    {
        $this->container['x_rate_limit_remaining'] = $x_rate_limit_remaining;

        return $this;
    }

    /**
     * Gets x_rate_limit_reset
     *
     * @return int|null
     */
    public function getXRateLimitReset()
    {
        return $this->container['x_rate_limit_reset'];
    }

    /**
     * Sets x_rate_limit_reset
     *
     * @param int|null $x_rate_limit_reset x_rate_limit_reset
     *
     * @return self
     */
    public function setXRateLimitReset($x_rate_limit_reset)
    {
        $this->container['x_rate_limit_reset'] = $x_rate_limit_reset;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


