<?php
/**
 * DefaultApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   Onelogin Devex Team
 * @link     https://onelogin.com
 */

/**
 * OneLogin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0.0-alpha.1
 * Generated by: https://onelogin.com
 * OpenAPI Generator version: 6.0.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://onelogin.com).
 * https://onelogin.com
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * DefaultApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   Onelogin Devex Team
 * @link     https://onelogin.com
 */
class DefaultApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for activateFactor
     *
     * .
     *
     */
    public function testActivateFactor()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for addAccessTokenClaim
     *
     * .
     *
     */
    public function testAddAccessTokenClaim()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for addClientApp
     *
     * .
     *
     */
    public function testAddClientApp()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for addRoleAdmins
     *
     * .
     *
     */
    public function testAddRoleAdmins()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for addRoleUsers
     *
     * .
     *
     */
    public function testAddRoleUsers()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for addScope
     *
     * .
     *
     */
    public function testAddScope()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for bulkMappingSort
     *
     * .
     *
     */
    public function testBulkMappingSort()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for bulkSort
     *
     * .
     *
     */
    public function testBulkSort()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createApp
     *
     * .
     *
     */
    public function testCreateApp()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createAuthorizationServer
     *
     * .
     *
     */
    public function testCreateAuthorizationServer()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createEnvironmentVariable
     *
     * .
     *
     */
    public function testCreateEnvironmentVariable()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createHook
     *
     * .
     *
     */
    public function testCreateHook()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createMapping
     *
     * .
     *
     */
    public function testCreateMapping()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createRiskRule
     *
     * .
     *
     */
    public function testCreateRiskRule()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createRoles
     *
     * .
     *
     */
    public function testCreateRoles()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createRule
     *
     * .
     *
     */
    public function testCreateRule()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createUser
     *
     * .
     *
     */
    public function testCreateUser()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteAccessTokenClaim
     *
     * .
     *
     */
    public function testDeleteAccessTokenClaim()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteApp
     *
     * .
     *
     */
    public function testDeleteApp()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteAppParameter
     *
     * .
     *
     */
    public function testDeleteAppParameter()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteAuthorizationServer
     *
     * .
     *
     */
    public function testDeleteAuthorizationServer()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteEnvironmentVariable
     *
     * .
     *
     */
    public function testDeleteEnvironmentVariable()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteFactor
     *
     * .
     *
     */
    public function testDeleteFactor()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteHook
     *
     * .
     *
     */
    public function testDeleteHook()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteMapping
     *
     * .
     *
     */
    public function testDeleteMapping()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteRiskRule
     *
     * .
     *
     */
    public function testDeleteRiskRule()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteRole
     *
     * .
     *
     */
    public function testDeleteRole()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteRule
     *
     * .
     *
     */
    public function testDeleteRule()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteScope
     *
     * .
     *
     */
    public function testDeleteScope()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteUser
     *
     * .
     *
     */
    public function testDeleteUser()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for dryRunMapping
     *
     * .
     *
     */
    public function testDryRunMapping()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for enrollFactor
     *
     * .
     *
     */
    public function testEnrollFactor()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for generateMfaToken
     *
     * .
     *
     */
    public function testGenerateMfaToken()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for generateSamlAssertion
     *
     * .
     *
     */
    public function testGenerateSamlAssertion()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for generateToken
     *
     * .
     *
     */
    public function testGenerateToken()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getApp
     *
     * .
     *
     */
    public function testGetApp()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getAuthorizationServer
     *
     * .
     *
     */
    public function testGetAuthorizationServer()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getAvailableFactors
     *
     * .
     *
     */
    public function testGetAvailableFactors()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getClientApps
     *
     * .
     *
     */
    public function testGetClientApps()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getEnrolledFactors
     *
     * .
     *
     */
    public function testGetEnrolledFactors()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getEnvironmentVariable
     *
     * .
     *
     */
    public function testGetEnvironmentVariable()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getHook
     *
     * .
     *
     */
    public function testGetHook()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getLogs
     *
     * .
     *
     */
    public function testGetLogs()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getMapping
     *
     * .
     *
     */
    public function testGetMapping()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getRateLimit
     *
     * .
     *
     */
    public function testGetRateLimit()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getRiskRule
     *
     * .
     *
     */
    public function testGetRiskRule()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getRiskScore
     *
     * .
     *
     */
    public function testGetRiskScore()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getRole
     *
     * .
     *
     */
    public function testGetRole()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getRoleAdmins
     *
     * .
     *
     */
    public function testGetRoleAdmins()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getRoleApps
     *
     * .
     *
     */
    public function testGetRoleApps()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getRoleUsers
     *
     * .
     *
     */
    public function testGetRoleUsers()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getRule
     *
     * .
     *
     */
    public function testGetRule()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getScoreInsights
     *
     * .
     *
     */
    public function testGetScoreInsights()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getUser
     *
     * .
     *
     */
    public function testGetUser()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getUserApps
     *
     * .
     *
     */
    public function testGetUserApps()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listAccessTokenClaims
     *
     * .
     *
     */
    public function testListAccessTokenClaims()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listActionValues
     *
     * .
     *
     */
    public function testListActionValues()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listActions
     *
     * .
     *
     */
    public function testListActions()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listAppUsers
     *
     * .
     *
     */
    public function testListAppUsers()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listApps
     *
     * .
     *
     */
    public function testListApps()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listAuthorizationServers
     *
     * .
     *
     */
    public function testListAuthorizationServers()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listConditionOperators
     *
     * .
     *
     */
    public function testListConditionOperators()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listConditionValues
     *
     * .
     *
     */
    public function testListConditionValues()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listConditions
     *
     * .
     *
     */
    public function testListConditions()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listConnectors
     *
     * .
     *
     */
    public function testListConnectors()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listEnvironmentVariables
     *
     * .
     *
     */
    public function testListEnvironmentVariables()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listHooks
     *
     * .
     *
     */
    public function testListHooks()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listMappingActionValues
     *
     * .
     *
     */
    public function testListMappingActionValues()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listMappingActions
     *
     * .
     *
     */
    public function testListMappingActions()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listMappingConditionOperators
     *
     * .
     *
     */
    public function testListMappingConditionOperators()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listMappingConditionValues
     *
     * .
     *
     */
    public function testListMappingConditionValues()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listMappingConditions
     *
     * .
     *
     */
    public function testListMappingConditions()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listMappings
     *
     * .
     *
     */
    public function testListMappings()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listRiskRules
     *
     * .
     *
     */
    public function testListRiskRules()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listRoles
     *
     * .
     *
     */
    public function testListRoles()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listRules
     *
     * .
     *
     */
    public function testListRules()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listScopes
     *
     * .
     *
     */
    public function testListScopes()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listUsers
     *
     * .
     *
     */
    public function testListUsers()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for removeClientApp
     *
     * .
     *
     */
    public function testRemoveClientApp()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for removeRoleAdmins
     *
     * .
     *
     */
    public function testRemoveRoleAdmins()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for removeRoleUsers
     *
     * .
     *
     */
    public function testRemoveRoleUsers()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for revokeToken
     *
     * .
     *
     */
    public function testRevokeToken()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for setRoleApps
     *
     * .
     *
     */
    public function testSetRoleApps()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for trackEvent
     *
     * .
     *
     */
    public function testTrackEvent()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateAccessTokenClaim
     *
     * .
     *
     */
    public function testUpdateAccessTokenClaim()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateApp
     *
     * .
     *
     */
    public function testUpdateApp()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateAuthorizationServer
     *
     * .
     *
     */
    public function testUpdateAuthorizationServer()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateClientApp
     *
     * .
     *
     */
    public function testUpdateClientApp()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateEnvironmentVariable
     *
     * .
     *
     */
    public function testUpdateEnvironmentVariable()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateHook
     *
     * .
     *
     */
    public function testUpdateHook()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateMapping
     *
     * .
     *
     */
    public function testUpdateMapping()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateRiskRule
     *
     * .
     *
     */
    public function testUpdateRiskRule()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateRole
     *
     * .
     *
     */
    public function testUpdateRole()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateRule
     *
     * .
     *
     */
    public function testUpdateRule()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateScope
     *
     * .
     *
     */
    public function testUpdateScope()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateUser
     *
     * .
     *
     */
    public function testUpdateUser()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for verifyEnrollment
     *
     * .
     *
     */
    public function testVerifyEnrollment()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for verifyEnrollmentVoiceProtect
     *
     * .
     *
     */
    public function testVerifyEnrollmentVoiceProtect()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for verifyFactor
     *
     * .
     *
     */
    public function testVerifyFactor()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for verifyFactorSaml
     *
     * .
     *
     */
    public function testVerifyFactorSaml()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for verifyFactorVoice
     *
     * .
     *
     */
    public function testVerifyFactorVoice()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
